### ISSUE TITLE
Problema com a instalação do face_recognition

### ISSUE THREAD

**Issue by TiagoCrippa** [WellingtonDev25/facialRecognition#1]
Sempre que tento instalar o pacote da um erro dizendo que não tenho o cmake e o dlib, porém estão instalados

**Comment by WellingtonDev25** [comment]
Olá Tiago, tem algumas possibilidades, por exemplo, caso esteja usando um ambiente virtual certifique-se de que o programa está realmente sendo executado dentro do ambiente aonde as bibliotecas foram instaladas, outro ponto é tentar criar um ambiente novo em outro local de preferencia usando o próprio prompt do Windows (python -m venv nome_da_venv) depois entrar no ambiente (nome_da_venv\Scripts\activate) e então fazer novamente a instalação das bibliotecas. não se esqueça de conferir se realmente as bibliotecas estão no ambiente usando (pip freeze).

**Comment by TiagoCrippa** [comment]
<img width="404" alt="Sem título" src="https://github.com/user-attachments/assets/cfb15911-529f-4381-9abe-d6d7d16ac1e2">
<img width="530" alt="Sem título2" src="https://github.com/user-attachments/assets/60460d8a-4dd0-4049-b054-d2a03df515b5">

são esses erros que estão dando e não está sendo feito em ambiente virtual

você utiliza windows ou mac? acho que esse pode ser o problema, estou tentando instalar esse pacote em um computador com windows

**Comment by WellingtonDev25** [comment]
@TiagoCrippa Para resolver esse erro você pode fazer a instalação do dlib de forma direta pelos arquivos binários, existem alguns tutoriais no youtube, vou deixar um aqui abaixo.

https://www.youtube.com/watch?v=pO150OCX-ac

**Comment by TiagoCrippa** [comment]
Deu certo!
Muito obrigado pela ajuda.
